### ISSUE TITLE
Ability to sort the results

### ISSUE THREAD

**Issue by pfrcks** [pinoceniccola/what-hn-says-webext#1]
Using the extension on generic domains like github.com show all the posts related to github.com sorted by popularity(i think). Is it possible to allow for an option to sort by time? 

The algolia api provides this facility and can be used for this.

**Comment by pinoceniccola** [comment]
Yes, it's sorted by popularity. When there are many results (more than 4 actually) you also get a link ("See all N stories on Algolia"). With it you can go to the HN Algolia website and refine the search further.

I don't think I'll build any other features. It's a quick tool for discovering HN thread about specific pages (in spite of that search is not strict on the URL submitted), but it is not intended to be a full Algolia search replacement.

Thanks.
