### ISSUE TITLE
Couldn't detect a popular HN post

### ISSUE THREAD

**Issue by Shihab-Shahriar** [pinoceniccola/what-hn-says-webext#5]
When I used this link -http://www.paulgraham.com/worked.html - the extension failed to detect that the story was available on HN.

However, if I remove the "www." part, it finds the story easily. This second version was shared on Hackernews.

**Comment by pinoceniccola** [comment]
> This second version was shared on Hackernews.

I think you already answered your question.

Or are you suggesting to always strip any "www." part in order to improve results?

**Comment by Shihab-Shahriar** [comment]
> Or are you suggesting to always strip any "www." part in order to improve results?

Yes, unless there are some side effects.
