### ISSUE TITLE
Add search for other sharing sites?

### ISSUE THREAD

**Issue by nc7s** [pinoceniccola/what-hn-says-webext#8]
Hi Pino, thanks for this great extension. I've grown the habit to click this every time I finished an interesting read ;) However, something feels missing: besides HN, there's lobste.rs, there's reddit, and the fediverse has lemmy. It's good to see different people talk about the same thing. Also, though unfortunate, some people have grown dislike to "the orange site".

I'm happy to implement this ;) but the name might have to be changed, something like "What They Say".

**Comment by stephane-klein** [comment]
@nc7s Have you found a solution, another extension to reach your goal? I'm looking for the same kind of functionality.

**Comment by nc7s** [comment]
@stephane-klein, yes: https://github.com/nc7s/whatwesay ;) This is a basic (but usable) prototype, supporting HN, Lobsters and Lemmy. Not yet uploaded to Firefox Add-ons and Chrome Web Store, I'm figuring out how. Help and feedback welcome!

**Comment by pinoceniccola** [comment]
@nc7s Good luck with your extension! Looks like yours has a much broader scope than mine, which I prefer to keep simple and focused on HN. Anyway, feel free to ping me for any question or feedback. Also, sorry for the delayed response. Closing this issue.
